### ISSUE TITLE
Menu des cours

### ISSUE THREAD

**Issue by titouanc** [UrLab/beta402#54]
Le menu d'arborescence des cours en haut de page était bien pratique sur la version p402, ce serait bien de l'implémenter dans DocHub

**Comment by C4ptainCrunch** [comment]
Bof, j'étais pas convaincu moi ^^
Et vu que maintenant on a les cours auxquels on est abonnées (=qu'on visite souvent) dans la barre de gauche l'intérêt est vachement plus limité non ?

**Comment by titouanc** [comment]
Use case: poster/trouver des documents/discussion pour des cours auxquels on n'est pas abonné en un minimum de navigation (exemple poster des documents pour des cours des années précédentes).
Facile de générer un bout d'html/json statique quand on construit le graphe des catégories et cours

**Comment by C4ptainCrunch** [comment]
Merci @titouanc :)

PS : we are reactive !
