### ISSUE TITLE
The courses catalog should reflect the change in courses' organisation.

### ISSUE THREAD

**Issue by BamBalaam** [UrLab/beta402#76]
Courses that changed years they are given at, new "year" names are now Bloc 1, Bloc 2 and Bloc 3, and other changes.

**Comment by BamBalaam** [comment]
Is it just a matter of changing https://github.com/UrLab/beta402/blob/master/parsing/tree.json ?

If so, I can fork and change that small detail.

**Comment by C4ptainCrunch** [comment]
Fixed :)
