### ISSUE TITLE
"Back" buttons still links to old course pages

### ISSUE THREAD

**Issue by BamBalaam** [UrLab/beta402#85]
Example: exploring a document on course info-f-305 --> using the button to go back to the course page --> be linked to course page "28".

**Comment by titouanc** [comment]
Which document exactly ?
I can't reproduce the bug here

**Comment by BamBalaam** [comment]
It's not a specific document, I have that in other classes too. Example with class "Bases de Données":

Opening a document (see URL of class)
![Image 1](http://i.imgur.com/oirN9i5.png)

Document works OK, no problem
![Image 2](http://i.imgur.com/nzHzIvK.png)

Using the "back" button.
![Image 3](http://i.imgur.com/Aystgf7.png)

404 page (check URL of class)
![Image 4](http://i.imgur.com/vRfK2Q1.png)

**Comment by titouanc** [comment]
Thx for the screenshots, it really helped ! I had not the bug, because it occurs only on smaller window sizes.
https://github.com/UrLab/beta402/blob/master/templates/documents/viewer_bar.html#L19

**Comment by BamBalaam** [comment]
First time ever my small screen was useful!
